#!/bin/sh

if ! git diff --cached --quiet -- petanca.sage; then
    echo -n 'Recompiling petanca.sage'
    sage --preparse petanca.sage
    mv petanca.sage.py petanca.py
    git add petanca.py
    echo ', done.'
fi
