

# This file was *autogenerated* from the file petanca.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2)
class Permutation(CombinatorialFreeModule.Element):

    def cycles(self):
        return sorted(term.leading_term().leading_monomial()
                      for term in self.terms())

    def is_cycle(self):
        return len(self) == _sage_const_1  and self.leading_coefficient() == _sage_const_1 

    def size(self):
        return int(sum(multiplicity * length
                       for length, multiplicity in self.items()))

    def is_improper(self):
        return any(coeff < _sage_const_0  for coeff in self.coefficients())

    def is_irreducible(self):
        return (self != PP(_sage_const_0 ) and self != PP(_sage_const_1 ) and
                self.factor() == Factorization([(self, _sage_const_1 )]))

    def is_prime(self):
        # https://doi.org/10.1016/j.tcs.2026.115879
        return False

    def sqrt(self, k=_sage_const_2 ):
        # https://doi.org/10.48550/arXiv.2604.04065
        if self.is_improper():
            raise NotImplementedError(
                f'unable to compute sqrt of {self}')
        root = PP(_sage_const_0 )
        power = PP(_sage_const_0 )
        while power.size() < self.size():
            root += min((self - power).cycles())
            power = root**k
        if power != self:
            return None
        return root

    def factor(self):
        if self == _sage_const_0 :
            raise ArithmeticError(
                'factorization of 0 is not defined')
        if self == _sage_const_1 :
            return Factorization([])
        if self.is_cycle():
            F = factor(self.size())
            return Factorization([(C[b**e], _sage_const_1 ) for b, e in F])
        for m, n in _proper_divisor_pairs(self.size()):
            for A in PP.irreducibles_of_size(m):
                for B in PP.of_size(n):
                    if A * B == self:
                        return Factorization([(A, _sage_const_1 )]) * B.factor()
        return Factorization([(self, _sage_const_1 )])

    def minimal_polynomial(self, var='X'):
        for deg in NN:
            basis = PP.up_closure(self.cycles())
            dim = len(basis)
            nvars = deg + _sage_const_1 
            A = matrix(ZZ, dim, nvars)
            power = PP(_sage_const_1 )
            for j in range(nvars):
                for i in range(dim):
                    k = basis[i].size()
                    A[i, j] = power.coefficient(k)
                power *= self
            kernel = A.right_kernel()
            if not kernel:
                continue
            coeffs = kernel.basis()[_sage_const_0 ]
            if coeffs[-_sage_const_1 ] < _sage_const_0 :
                coeffs *= -_sage_const_1 
            R = ZZ[var]; (X,) = R._first_ngens(1)
            return R.sum(coeffs[i] * X**i
                         for i in range(nvars))


class Permutations(CombinatorialFreeModule):

    Element = Permutation

    def __init__(self):
        CombinatorialFreeModule.__init__(
            self, ZZ, PositiveIntegers(), prefix='C',
            category=Category.join((AlgebrasWithBasis(ZZ),
                                    CommutativeRings())))

    def product_on_basis(self, m, n):
        return gcd(m, n) * C[lcm(m, n)]

    def one_basis(self):
        return _sage_const_1 

    def _repr_(self):
        return '(Semi)ring of Permutations'

    def __iter__(self):
        return (A for size in NN
                for A in PP.of_size(size))

    def is_field(self):
        return False

    def is_integral_domain(self):
        return False

    @staticmethod
    def irreducibles():
        return (A for A in PP
                if A.is_irreducible())

    @staticmethod
    def of_size(size):
        return (PP.sum(C[n] for n in partition)
                for partition in Partitions(size))

    @staticmethod
    def irreducibles_of_size(size):
        return (A for A in PP.of_size(size)
                if A.is_irreducible())

    @staticmethod
    def up_closure(generators):
        return sorted(set(PP.prod(S).leading_monomial()
                          for S in powerset(generators)))

    @staticmethod
    def down_closure(generators):
        return sorted(set(div for gen in generators
                          for term in gen.terms()
                          for cycle in term.cycles()
                          for div in divisors(cycle)))

    def _roots_univariate_polynomial(self, P, *args, **kwargs):
        if _is_root_extraction(P):
            return _roots_extraction(P)
        else:
            return _roots_generic(P)


def _proper_divisor_pairs(n):
    return ((d, n // d)
             for d in range(_sage_const_2 , isqrt(n) + _sage_const_1 )
             if n % d == _sage_const_0 )


def _cycles(P):
    return sorted(x for c in P.coefficients()
                  for x in c.cycles())


def _is_univariate(P):
    return len(P.parent().gens()) <= _sage_const_1 


def _is_root_extraction(P):
    return (len(P.terms()) == _sage_const_2  and min(P.exponents()) == _sage_const_0 
            or len(P.terms()) == _sage_const_1 ) and P.leading_coefficient() == _sage_const_1 


def _roots_extraction(P):
    A = -P.constant_coefficient()
    root = A.sqrt(P.degree())
    return [root] if root is not None else []


def _roots_generic(P):
    cycle_len = lambda i: i
    cardinality = PP.module_morphism(cycle_len, codomain=ZZ)
    q = P.map_coefficients(cardinality)
    roots = q.roots(multiplicities=False)
    return [A for size in roots
            for A in PP.of_size(size)
            if P(A) == _sage_const_0 ]


# Constants

PP = Permutations()
C = PP.basis()
_R = PP['X']; (X,) = _R._first_ngens(1)


# Code for pseudo-injective polynomials, under development

from sage.functions.log import logb


def _root_pseudo_injective(self, P):
    # https://doi.org/10.48550/arXiv.2604.04065
    B = -P.constant_coefficient()
    P += B
    X = PP(_sage_const_0 )
    seed = _seed(P)
    while P(X) < B:
        X += C[_anti_lcm(seed, B - P(X))]
    if P(X) != B:
        return None
    return X


def _is_pseudo_injective(P):
    const_coeff = P.coefficients()[_sage_const_0 ]
    nonconst_coeffs = P.coefficients()[_sage_const_1 :]
    if const_coeff > _sage_const_0  or any(PP(coeff).is_improper()
                              for coeff in nonconst_coeffs):
        return False
    cycles = _cycles(P)
    seed = cycles[_sage_const_0 ].size()
    return all(cycle.size() % seed == _sage_const_0 
               for cycle in cycles)


def _anti_lcm(a, b):
    if a not in NN:
        a = min(a.cycles()).size()
    if b not in NN:
        b = min(b.cycles()).size()
    if b % a != _sage_const_0 :
        raise ValueError(f'{a} does not divide {b}')
    k = ceil(logb(b, _sage_const_2 ))
    return gcd(int(b/a)**k, b)


def _seed(P):
    cycles = _cycles(P)
    return cycles[_sage_const_0 ].size()

